version: '3'
services:
  app:
    build:
      context:
      dockerfile: Dockerfile
    container_name: app_api_register
    image: api_register_image
    restart: unless-stopped
    environment:
      DB_ADDRESS: "mongodb://mongodb:27017"
      DB_NAME: "api-register"
      PORT: 8080
      WORKERS: 3
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb_api_register
    restart: unless-stopped
    command: mongod
    # volumes:
     # - mongodbdata:/data/db
    networks:
     - backend

networks:
  backend: 
    driver: bridge
